### ISSUE TITLE
Configure Base API docs with redocly

### ISSUE THREAD

**Issue by RashJrEdmund** [Wikidata-Cameroon/WMA_HackKmer_Yaounde_Backend#2]
- Do base setup for API documentation with [redoc](https://github.com/Redocly/redoc) and follow OpenAPI standards.

- see example on how to setup schemas [here](https://github.com/Redocly/redoc/blob/main/demo/museum.yaml)

- Then the dos team will continue from here on

**Comment by eugeneegbe** [comment]
@solonkonora!

**Comment by VictorNico** [comment]
@RashJrEdmund Really God Idea and also good job, thanks for this contribution. Lets us move together.

**Comment by RashJrEdmund** [comment]
absolutely.

let me finish, setting up redoc. they'll continue from that foundation.
